/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',

    config: {
        activeItem: 1,
        items: [
            {
                xtype: 'container',
                title: 'Dashboard',
                iconCls: 'info',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'container',
                        flex: 1,
                        html: 'logo?'
                    },
                    {
                        xtype: 'button',
                        text: 'MyButton1'
                    },
                    {
                        xtype: 'list',
                        flex: 1,
                        itemTpl: [
                            '<div>List Item {string}</div>'
                        ]
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                title: 'Schedule',
                iconCls: 'info',
                items: [
                    {
                        xtype: 'container',
                        title: 'Bus',
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'list',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Trolley',
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'list',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Train',
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'list',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Subway',
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'list',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'navigationview',
                title: 'Trip Planner',
                iconCls: 'info',
                items: [
                    {
                        xtype: 'formpanel',
                        items: [
                            {
                                xtype: 'fieldset',
                                title: 'MyFieldSet',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        label: 'To'
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: 'From'
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: 'Time'
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'MyButton'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                title: 'Map',
                iconCls: 'info',
                items: [
                    {
                        xtype: 'map',
                        title: 'Rail'
                    },
                    {
                        xtype: 'map',
                        title: 'Buses'
                    },
                    {
                        xtype: 'map',
                        title: 'Trains'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                title: 'Bookmarks',
                iconCls: 'info',
                items: [
                    {
                        xtype: 'container',
                        title: 'Trips',
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'list',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Lines',
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'list',
                                itemTpl: [
                                    '<div>List Item {string}</div>'
                                ]
                            }
                        ]
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});